2023-05-08 15:00:47,670 - INFO - 57513 - Start Running clusterings
2023-05-09 00:32:53,958 - ERROR - 4064 -                                                      0  ... EXP_TRAIN_TEST_BUCKET_SIZE
0    [0.022239360958337784, 0.008565396070480347, 0...  ...                          1
1    [0.02688870206475258, 0.029336608946323395, 0....  ...                          4
2    [0.018209433183073997, 0.008087853901088238, 0...  ...                          4
3    [0.012460590340197086, 0.009455552324652672, 0...  ...                          2
4    [0.014029838144779205, 0.006368839647620916, 0...  ...                          1
..                                                 ...  ...                        ...
445  [0.018209433183073997, 0.008087853901088238, 0...  ...                          4
446  [0.012566844001412392, 0.012096766382455826, 0...  ...                          3
447  [0.07150785624980927, 0.006368839647620916, 0....  ...                          0
448  [0.09445736557245255, 0.009133503772318363, 0....  ...                          3
449  [0.02688870206475258, 0.029336608946323395, 0....  ...                          4

[450 rows x 59 columns]
Traceback (most recent call last):
  File "/Users/macbook/Documents/uni/KPDataMining/Data-Mining/src/datasets/base_loader.py", line 89, in load_single_csv
    pd.read_csv(
  File "/Users/macbook/Library/Caches/pypoetry/virtualenvs/data_mining_big_data_group_project-eXp1fT7m-py3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Library/Caches/pypoetry/virtualenvs/data_mining_big_data_group_project-eXp1fT7m-py3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Library/Caches/pypoetry/virtualenvs/data_mining_big_data_group_project-eXp1fT7m-py3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Library/Caches/pypoetry/virtualenvs/data_mining_big_data_group_project-eXp1fT7m-py3.11/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 812, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 889, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1034, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1088, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1163, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "/Users/macbook/Library/Caches/pypoetry/virtualenvs/data_mining_big_data_group_project-eXp1fT7m-py3.11/lib/python3.11/site-packages/pandas/core/dtypes/common.py", line 1335, in is_extension_array_dtype
    def is_extension_array_dtype(arr_or_dtype) -> bool:
    
KeyboardInterrupt
